version: 1
formatters:
  simple:
    format: '%(asctime)s :: %(name)-30s :: %(levelname)-8s :: %(message)s'
filters:
  healthcheck_filter:
    "()": app.log.filters.HealthCheckFilter
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
    filters:
      - healthcheck_filter
loggers:
  uvicorn.error:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
