[tool.poetry]
name = "backend"
version = "0.1.0"
description = "SLAS - SLPortal Backend"
authors = ["Danny Rehl", "Dustin Heckmann"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {version = "^0.95.0", extras = ["all"]}
pyjwt = "^2.6.0"
fastapi-auth-middleware = "^1.0.2"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pylint = "^2.15.0"
isort = "^5.12.0"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
